<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'invalid format' => 'Указан неверный счёт Payeer.',
    'transferHimselfForbidden' => 'Указан неверный счёт Payeer.',
    'toError' => 'Указан неверный счёт Payeer.',
    'curIn invalid' => 'Валюта списания не поддерживается.',
    'curOut invalid' => 'Валюта получения не поддерживается.',
    'This type of exchange is not possible' => 'Автоматический обмен валюты curIn на curOut временно запрещен.',
    'pay_sys_no_isset' => 'Платежное направление отключено или не существует.',
    'cur_no_pay_sys' => 'Несуществующая валюта получения.',
    'sum_less_min' => 'Сумма получения меньше минимальной.',
    'sum_more_max' => 'Сумма получения больше максимальной.',
    'output_block' => 'У нас возникли вопросы к Вашей деятельности. Пожалуйста, обратитесь в Службу поддержки.',
    'balans_no' => 'Недостаточно средств для вывода.',
    'balans_no_hold' => 'Недостаточно средств для вывода с учетом ограничений по аккаунту.',
    'balance_sys_no' => 'Нет резерва для создания выплаты в данном направлении.',
    'Invalid Payee_Account' => 'Указан неверный счёт Perfect Money.',
    'Payee and payer accounts has different types' => 'Указанный счёт не является долларовым счётом Perfect Money.',
    'Now you will be redirected to the payment system.' => 'Выполняется перенаправление на платежную систему.',
];
